package compare;

/**
 * Report chrome shared by the HTML outputs. Mirrors REPORT_CSS / REPORT_JS in
 * compare_json_xml.py so the Python and Java reports render identically.
 */
final class Theme {

    private Theme() {}

    static final String CSS =
            "*{box-sizing:border-box}"
            + "body{margin:0;background:#eef1f8;color:#1f2937;"
            + "font:13.5px/1.5 \"Segoe UI\",Inter,system-ui,-apple-system,sans-serif}"
            + ".page{max-width:1560px;margin:0 auto;padding:18px 20px 60px}"
            + ".hero{background:linear-gradient(120deg,#7c4fe0 0%,#5b6ff0 55%,#3b82f6 100%);"
            + "border-radius:14px;padding:26px 24px;text-align:center;color:#fff;"
            + "box-shadow:0 10px 26px rgba(59,88,180,.28)}"
            + ".hero h1{margin:0 0 6px;font-size:27px;font-weight:700;letter-spacing:.2px}"
            + ".hero .sub{font-size:13px;opacity:.95}"
            + ".hero .meta{margin-top:8px;font-size:11.5px;opacity:.85}"
            + ".tabs{display:flex;gap:2px;flex-wrap:wrap;background:#fff;border:1px solid #dfe3ee;"
            + "border-radius:10px;margin:14px 0;padding:4px}"
            + ".tab{background:transparent;border:0;border-bottom:3px solid transparent;color:#5b6478;"
            + "font:inherit;font-weight:600;padding:10px 14px;cursor:pointer;white-space:nowrap;"
            + "border-radius:6px 6px 0 0}"
            + ".tab em{font-style:normal;font-weight:500;color:#98a1b5;font-size:11.5px}"
            + ".tab:hover{background:#f3f5fb}"
            + ".tab.is-active{color:#3b6fd4;border-bottom-color:#3b6fd4;background:#f3f7ff}"
            + ".panel{background:linear-gradient(120deg,#5b8bf0,#7b6ae8);border-radius:14px;padding:18px;"
            + "color:#fff;box-shadow:0 8px 20px rgba(59,88,180,.22)}"
            + ".panel h2{margin:0 0 14px;text-align:center;font-size:17px;font-weight:700}"
            + ".stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}"
            + ".stat{background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.28);"
            + "border-radius:11px;padding:14px 16px}"
            + ".stat .label{display:block;font-size:11.5px;opacity:.92;margin-bottom:6px}"
            + ".stat .num{font-size:26px;font-weight:700}"
            + ".files{display:flex;gap:18px;flex-wrap:wrap;margin-top:14px;font-size:11.5px;opacity:.92}"
            + ".files b{opacity:.8;font-weight:600;margin-right:5px}"
            + ".views{display:flex;gap:20px;border-bottom:2px solid #e2e6f0;margin-top:18px;flex-wrap:wrap}"
            + ".view{background:none;border:0;border-bottom:3px solid transparent;color:#5b6478;"
            + "font:inherit;font-weight:600;padding:10px 2px;cursor:pointer;margin-bottom:-2px}"
            + ".view:hover{color:#1f2937}"
            + ".view.is-active{color:#3b6fd4;border-bottom-color:#3b6fd4}"
            + ".view.is-active[data-view=\"compared\"]{color:#3b6fd4;border-bottom-color:#3b6fd4}"
            + ".view.is-active[data-view=\"matched\"]{color:#15803d;border-bottom-color:#16a34a}"
            + ".view.is-active[data-view=\"problems\"]{color:#dc2626;border-bottom-color:#dc2626}"
            + ".view.is-active[data-view=\"coverage\"]{color:#4f46e5;border-bottom-color:#4f46e5}"
            + ".view .dot{display:inline-block;width:8px;height:8px;border-radius:50%;"
            + "margin-right:7px;background:#3b6fd4}"
            + ".view[data-view=\"matched\"] .dot{background:#16a34a}"
            + ".view[data-view=\"problems\"] .dot{background:#dc2626}"
            + ".view[data-view=\"coverage\"] .dot{background:#4f46e5}"
            + ".toolbar{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin:12px 0}"
            + ".toolbar input,.toolbar button{font:inherit;border:1px solid #d3d9e8;background:#fff;"
            + "color:#1f2937;border-radius:8px;padding:9px 12px}"
            + ".toolbar input{min-width:320px}"
            + ".toolbar input:focus{outline:2px solid #b9ccf5;border-color:#7aa2e8}"
            + ".toolbar button{cursor:pointer;font-weight:600}"
            + ".toolbar button:hover{border-color:#7aa2e8}"
            + ".toolbar .primary{background:#3b6fd4;border-color:#3b6fd4;color:#fff}"
            + ".toolbar .count{color:#5b6478;font-size:12.5px}"
            + ".chips{display:flex;gap:7px;flex-wrap:wrap;margin:14px 0 2px}"
            + ".chip{display:flex;align-items:baseline;gap:6px;cursor:pointer;font:inherit;background:#fff;"
            + "border:1px solid #dfe3ee;border-left:4px solid var(--tone);border-radius:9px;padding:7px 11px}"
            + ".chip b{font-size:15px;color:var(--tone)}"
            + ".chip span{font-size:10.5px;color:#6b7385;letter-spacing:.03em}"
            + ".chip.off{opacity:.4}"
            + ".notice{border-radius:9px;padding:11px 14px;font-size:12.5px;margin:14px 0;border:1px solid}"
            + ".notice.warn{background:#fff8e6;border-color:#f3d99b;color:#8a5a00}"
            + ".notice.ok{background:#eafaf0;border-color:#b7e6c9;color:#166534}"
            + ".notice.info{background:#eef0ff;border-color:#c7cbf7;color:#3730a3}"
            + ".rows-title{color:#15803d;font-size:15px;margin:18px 0 9px;padding-bottom:7px;"
            + "border-bottom:2px solid #16a34a}"
            + ".wrap{background:#fff;border:1px solid #dfe3ee;border-radius:11px;overflow:auto;"
            + "box-shadow:0 2px 8px rgba(31,41,55,.05)}"
            + "table{border-collapse:collapse;width:100%}"
            + "thead th{position:sticky;top:0;background:linear-gradient(#1c9c53,#15803d);color:#fff;"
            + "text-align:left;font-size:10.5px;letter-spacing:.07em;text-transform:uppercase;padding:10px 11px}"
            + "tbody td{border-bottom:1px solid #eceff6;padding:9px 11px;vertical-align:top}"
            + "tbody tr:hover{background:#f2f7ff}"
            + ".mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px}"
            + ".value{max-width:330px;overflow-wrap:anywhere}"
            + ".path{color:#5f6b82;max-width:230px;overflow-wrap:anywhere}"
            + ".detail{color:#6b7385;max-width:270px;overflow-wrap:anywhere}"
            + ".pill{display:inline-block;border-radius:20px;font-size:10px;font-weight:700;"
            + "letter-spacing:.04em;padding:3px 9px;white-space:nowrap}"
            + ".dash{color:#aab2c4}"
            + "a{color:#3b6fd4}";

    static final String JS =
            "const rows=[...document.querySelectorAll(\"tbody tr\")];"
            + "const chips=[...document.querySelectorAll(\".chip\")];"
            + "const ALL=chips.map(c=>c.dataset.status);"
            + "const MATCHED=[\"MATCH\",\"NORMALIZED_MATCH\"];"
            + "const PROBLEMS=[\"MISMATCH\",\"MISSING_IN_JSON\",\"MISSING_IN_XML\","
            + "  \"UNMATCHED_JSON_ROW\",\"UNMATCHED_XML_ROW\"];"
            + "const COVERAGE=[\"UNMAPPED_IN_JSON\",\"UNMAPPED_IN_XML\"];"
            + "const COMPARED=ALL.filter(s=>!COVERAGE.includes(s));"
            + "const active=new Set(COMPARED);"
            + "const search=document.querySelector(\"#q\");"
            + "let group=\"*\";"
            + "function apply(){"
            + "  const term=search.value.trim().toLowerCase();"
            + "  let shown=0;"
            + "  for(const row of rows){"
            + "    const visible=active.has(row.dataset.status)"
            + "      &&(group===\"*\"||row.dataset.group===group)"
            + "      &&(!term||row.dataset.hay.includes(term));"
            + "    row.hidden=!visible;"
            + "    if(visible)shown++;"
            + "  }"
            + "  document.querySelector(\"#shown\").textContent=shown;"
            + "  chips.forEach(c=>c.classList.toggle(\"off\",!active.has(c.dataset.status)));"
            + "}"
            + "function setStatuses(list){active.clear();list.forEach(s=>active.add(s));apply();}"
            + "chips.forEach(chip=>chip.onclick=()=>{"
            + "  const status=chip.dataset.status;"
            + "  if(active.has(status))active.delete(status);else active.add(status);"
            + "  apply();"
            + "});"
            + "document.querySelectorAll(\".tab\").forEach(tab=>tab.onclick=()=>{"
            + "  document.querySelectorAll(\".tab\").forEach(t=>t.classList.remove(\"is-active\"));"
            + "  tab.classList.add(\"is-active\");"
            + "  group=tab.dataset.group;"
            + "  apply();"
            + "});"
            + "document.querySelectorAll(\".view\").forEach(view=>view.onclick=()=>{"
            + "  document.querySelectorAll(\".view\").forEach(v=>v.classList.remove(\"is-active\"));"
            + "  view.classList.add(\"is-active\");"
            + "  const mode=view.dataset.view;"
            + "  setStatuses(mode===\"matched\"?MATCHED:mode===\"problems\"?PROBLEMS"
            + "    :mode===\"coverage\"?COVERAGE:COMPARED);"
            + "});"
            + "search.oninput=apply;"
            + "document.querySelector(\"#reset\").onclick=()=>{"
            + "  search.value=\"\";group=\"*\";"
            + "  document.querySelectorAll(\".tab\").forEach((t,i)=>t.classList.toggle(\"is-active\",i===0));"
            + "  document.querySelectorAll(\".view\").forEach((v,i)=>v.classList.toggle(\"is-active\",i===0));"
            + "  setStatuses(COMPARED);"
            + "};"
            + "document.querySelector(\"#csv\").onclick=()=>{"
            + "  const header=[\"group\",\"key\",\"path\",\"status\",\"jsonValue\",\"xmlMappedValue\","
            + "    \"jsonPath\",\"xmlPath\",\"detail\"];"
            + "  const quote=v=>'\"'+String(v).split('\"').join('\"\"')+'\"';"
            + "  const data=[header,...rows.filter(r=>!r.hidden).map(r=>JSON.parse(r.dataset.values))];"
            + "  const blob=new Blob([data.map(r=>r.map(quote).join(\",\")).join(\"\\n\")],{type:\"text/csv\"});"
            + "  const link=document.createElement(\"a\");"
            + "  link.href=URL.createObjectURL(blob);"
            + "  link.download=\"filtered-report.csv\";"
            + "  link.click();"
            + "};"
            + "apply();";
}
